apiVersion: batch/v1
kind: Job
metadata:
  name: parse-tag
spec:
  template:
    metadata:
      name: parse-tag
    spec:
      containers:
      - name: parser
        image: loqutus/tcpdump_parser:tag
        command: ["/bin/sh"]
        args:
         - "-c"
         - >
           cd /
           wget -c https://storage.googleapis.com/interview-test/dump.txt
           /parse.py
      restartPolicy: Never
